services:
    utilities:
        image: k8spaasclusterdesign.azurecr.io/tools/utilities:0.1.0
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        environment:
            - KUBECONFIG=/code/kube-config.yaml
        volumes:
            - .:/code
        working_dir: /code
        stdin_open: true
        tty: true
